#!/usr/bin/env python
import os
from kliko.validate import validate


# TODO: should we let the user add input/work path to the input or should we do this automatically?
#from kliko import input_path

# TODO: we can make this container split IO by copying the MS first.


parameters = validate()
args = " ".join([k + "=" + str(v) for k, v in parameters.items()])
cmd = '/usr/bin/lwimager ' + args
print("starting: " + cmd)
os.system(cmd)
